// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test/order.proto
// Protobuf C++ Version: 6.33.2

#ifndef test_2forder_2eproto_2epb_2eh
#define test_2forder_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/service.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_test_2forder_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_test_2forder_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_test_2forder_2eproto;
}  // extern "C"
class makeOrderRequest;
struct makeOrderRequestDefaultTypeInternal;
extern makeOrderRequestDefaultTypeInternal _makeOrderRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull makeOrderRequest_class_data_;
class makeOrderResponse;
struct makeOrderResponseDefaultTypeInternal;
extern makeOrderResponseDefaultTypeInternal _makeOrderResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull makeOrderResponse_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class makeOrderResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:makeOrderResponse) */ {
 public:
  inline makeOrderResponse() : makeOrderResponse(nullptr) {}
  ~makeOrderResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(makeOrderResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(makeOrderResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR makeOrderResponse(::google::protobuf::internal::ConstantInitialized);

  inline makeOrderResponse(const makeOrderResponse& from) : makeOrderResponse(nullptr, from) {}
  inline makeOrderResponse(makeOrderResponse&& from) noexcept
      : makeOrderResponse(nullptr, ::std::move(from)) {}
  inline makeOrderResponse& operator=(const makeOrderResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline makeOrderResponse& operator=(makeOrderResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const makeOrderResponse& default_instance() {
    return *reinterpret_cast<const makeOrderResponse*>(
        &_makeOrderResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(makeOrderResponse& a, makeOrderResponse& b) { a.Swap(&b); }
  inline void Swap(makeOrderResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(makeOrderResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  makeOrderResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<makeOrderResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const makeOrderResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const makeOrderResponse& from) { makeOrderResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(makeOrderResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "makeOrderResponse"; }

  explicit makeOrderResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  makeOrderResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const makeOrderResponse& from);
  makeOrderResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, makeOrderResponse&& from) noexcept
      : makeOrderResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResInfoFieldNumber = 2,
    kOrderIdFieldNumber = 3,
    kRetCodeFieldNumber = 1,
  };
  // string res_info = 2;
  void clear_res_info() ;
  const ::std::string& res_info() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_res_info(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_res_info();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_res_info();
  void set_allocated_res_info(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_res_info() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_res_info(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_res_info();

  public:
  // string order_id = 3;
  void clear_order_id() ;
  const ::std::string& order_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_order_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_order_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_order_id();
  void set_allocated_order_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_order_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_order_id();

  public:
  // int32 ret_code = 1;
  void clear_ret_code() ;
  ::int32_t ret_code() const;
  void set_ret_code(::int32_t value);

  private:
  ::int32_t _internal_ret_code() const;
  void _internal_set_ret_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:makeOrderResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const makeOrderResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr res_info_;
    ::google::protobuf::internal::ArenaStringPtr order_id_;
    ::int32_t ret_code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2forder_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull makeOrderResponse_class_data_;
// -------------------------------------------------------------------

class makeOrderRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:makeOrderRequest) */ {
 public:
  inline makeOrderRequest() : makeOrderRequest(nullptr) {}
  ~makeOrderRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(makeOrderRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(makeOrderRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR makeOrderRequest(::google::protobuf::internal::ConstantInitialized);

  inline makeOrderRequest(const makeOrderRequest& from) : makeOrderRequest(nullptr, from) {}
  inline makeOrderRequest(makeOrderRequest&& from) noexcept
      : makeOrderRequest(nullptr, ::std::move(from)) {}
  inline makeOrderRequest& operator=(const makeOrderRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline makeOrderRequest& operator=(makeOrderRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const makeOrderRequest& default_instance() {
    return *reinterpret_cast<const makeOrderRequest*>(
        &_makeOrderRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(makeOrderRequest& a, makeOrderRequest& b) { a.Swap(&b); }
  inline void Swap(makeOrderRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(makeOrderRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  makeOrderRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<makeOrderRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const makeOrderRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const makeOrderRequest& from) { makeOrderRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(makeOrderRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "makeOrderRequest"; }

  explicit makeOrderRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  makeOrderRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const makeOrderRequest& from);
  makeOrderRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, makeOrderRequest&& from) noexcept
      : makeOrderRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGoodsFieldNumber = 2,
    kPriceFieldNumber = 1,
  };
  // string goods = 2;
  void clear_goods() ;
  const ::std::string& goods() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_goods(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_goods();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_goods();
  void set_allocated_goods(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_goods() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_goods(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_goods();

  public:
  // int32 price = 1;
  void clear_price() ;
  ::int32_t price() const;
  void set_price(::int32_t value);

  private:
  ::int32_t _internal_price() const;
  void _internal_set_price(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:makeOrderRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 30,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const makeOrderRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr goods_;
    ::int32_t price_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2forder_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull makeOrderRequest_class_data_;

// ===================================================================


// -------------------------------------------------------------------

class Order_Stub;
class Order : public ::google::protobuf::Service {
 protected:
  Order() = default;

 public:
  using Stub = Order_Stub;

  Order(const Order&) = delete;
  Order& operator=(const Order&) = delete;
  virtual ~Order() = default;

  static const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL descriptor();

  virtual void makeOrder(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                        const ::makeOrderRequest* PROTOBUF_NONNULL request,
                        ::makeOrderResponse* PROTOBUF_NONNULL response,
                        ::google::protobuf::Closure* PROTOBUF_NULLABLE done);

  // implements Service ----------------------------------------------
  const ::google::protobuf::ServiceDescriptor* PROTOBUF_NONNULL GetDescriptor() override;

  void CallMethod(
      const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method,
      ::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
      const ::google::protobuf::Message* PROTOBUF_NONNULL request,
      ::google::protobuf::Message* PROTOBUF_NONNULL response,
      ::google::protobuf::Closure* PROTOBUF_NULLABLE done) override;

  const ::google::protobuf::Message& GetRequestPrototype(
      const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const override;

  const ::google::protobuf::Message& GetResponsePrototype(
      const ::google::protobuf::MethodDescriptor* PROTOBUF_NONNULL method) const override;
};

class Order_Stub final : public Order {
 public:
  Order_Stub(::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel);
  Order_Stub(::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);

  Order_Stub(const Order_Stub&) = delete;
  Order_Stub& operator=(const Order_Stub&) = delete;

  ~Order_Stub() override;

  inline ::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel() { return channel_; }

  // implements Order ------------------------------------------
  void makeOrder(::google::protobuf::RpcController* PROTOBUF_NULLABLE controller,
                        const ::makeOrderRequest* PROTOBUF_NONNULL request,
                        ::makeOrderResponse* PROTOBUF_NONNULL response,
                        ::google::protobuf::Closure* PROTOBUF_NULLABLE done) override;

 private:
  ::google::protobuf::RpcChannel* PROTOBUF_NULLABLE channel_;
  bool owns_channel_;
};
// ===================================================================



// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// makeOrderRequest

// int32 price = 1;
inline void makeOrderRequest::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t makeOrderRequest::price() const {
  // @@protoc_insertion_point(field_get:makeOrderRequest.price)
  return _internal_price();
}
inline void makeOrderRequest::set_price(::int32_t value) {
  _internal_set_price(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:makeOrderRequest.price)
}
inline ::int32_t makeOrderRequest::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void makeOrderRequest::_internal_set_price(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// string goods = 2;
inline void makeOrderRequest::clear_goods() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.goods_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& makeOrderRequest::goods() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:makeOrderRequest.goods)
  return _internal_goods();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void makeOrderRequest::set_goods(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.goods_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:makeOrderRequest.goods)
}
inline ::std::string* PROTOBUF_NONNULL makeOrderRequest::mutable_goods()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_goods();
  // @@protoc_insertion_point(field_mutable:makeOrderRequest.goods)
  return _s;
}
inline const ::std::string& makeOrderRequest::_internal_goods() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.goods_.Get();
}
inline void makeOrderRequest::_internal_set_goods(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.goods_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL makeOrderRequest::_internal_mutable_goods() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.goods_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE makeOrderRequest::release_goods() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:makeOrderRequest.goods)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.goods_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.goods_.Set("", GetArena());
  }
  return released;
}
inline void makeOrderRequest::set_allocated_goods(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.goods_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.goods_.IsDefault()) {
    _impl_.goods_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:makeOrderRequest.goods)
}

// -------------------------------------------------------------------

// makeOrderResponse

// int32 ret_code = 1;
inline void makeOrderResponse::clear_ret_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t makeOrderResponse::ret_code() const {
  // @@protoc_insertion_point(field_get:makeOrderResponse.ret_code)
  return _internal_ret_code();
}
inline void makeOrderResponse::set_ret_code(::int32_t value) {
  _internal_set_ret_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:makeOrderResponse.ret_code)
}
inline ::int32_t makeOrderResponse::_internal_ret_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ret_code_;
}
inline void makeOrderResponse::_internal_set_ret_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_code_ = value;
}

// string res_info = 2;
inline void makeOrderResponse::clear_res_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.res_info_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& makeOrderResponse::res_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:makeOrderResponse.res_info)
  return _internal_res_info();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void makeOrderResponse::set_res_info(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.res_info_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:makeOrderResponse.res_info)
}
inline ::std::string* PROTOBUF_NONNULL makeOrderResponse::mutable_res_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_res_info();
  // @@protoc_insertion_point(field_mutable:makeOrderResponse.res_info)
  return _s;
}
inline const ::std::string& makeOrderResponse::_internal_res_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.res_info_.Get();
}
inline void makeOrderResponse::_internal_set_res_info(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.res_info_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL makeOrderResponse::_internal_mutable_res_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.res_info_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE makeOrderResponse::release_res_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:makeOrderResponse.res_info)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.res_info_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.res_info_.Set("", GetArena());
  }
  return released;
}
inline void makeOrderResponse::set_allocated_res_info(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.res_info_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.res_info_.IsDefault()) {
    _impl_.res_info_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:makeOrderResponse.res_info)
}

// string order_id = 3;
inline void makeOrderResponse::clear_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& makeOrderResponse::order_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:makeOrderResponse.order_id)
  return _internal_order_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void makeOrderResponse::set_order_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.order_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:makeOrderResponse.order_id)
}
inline ::std::string* PROTOBUF_NONNULL makeOrderResponse::mutable_order_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_order_id();
  // @@protoc_insertion_point(field_mutable:makeOrderResponse.order_id)
  return _s;
}
inline const ::std::string& makeOrderResponse::_internal_order_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_id_.Get();
}
inline void makeOrderResponse::_internal_set_order_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL makeOrderResponse::_internal_mutable_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.order_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE makeOrderResponse::release_order_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:makeOrderResponse.order_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.order_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.order_id_.Set("", GetArena());
  }
  return released;
}
inline void makeOrderResponse::set_allocated_order_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.order_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.order_id_.IsDefault()) {
    _impl_.order_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:makeOrderResponse.order_id)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // test_2forder_2eproto_2epb_2eh
